hostname = mb3admin.com

^https:\/\/mb3admin\.com\/admin\/service\/registration\/(validateDevice|validate|getStatus) url script-echo-response https://raw.githubusercontent.com/qvshuo/QuantumultX/main/emby_premium.js
