name: Sync Spotify Config from app2smile

on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Sync File
        run: |
          NOW=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          curl -fsSL https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.conf -o spotify.conf

      - name: Commit and Push
        run: |
          NOW=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add spotify.conf
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync spotify.conf $NOW (UTC+8)"
            git push
          else
            echo "No changes detected, skipping push."
          fi
