name: Sync Config Files

on:
  schedule:
    - cron: "30 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Sync Files
        run: |
          NOW=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          curl -fsSL https://gist.githubusercontent.com/RavelloH/68ed0626dae69a1ce7c8ad6887087ea1/raw/main.snippet -o RedditAutoTranslate.snippet
          curl -fsSL https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.conf -o SpotifyPremium.conf
          curl -fsSL https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/Youtube.snippet -o YouTubeAdBlock.conf
          curl -fsSL https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/AmapAds.conf -o AMapAdBlock.conf
          curl -fsSL https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/NeteaseAds.conf -o NeteaseCloudMusicAdBlock.conf
          curl -fsSL https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/RedditAds.conf -o RedditAdBlock.conf
          curl -fsSL https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/GoofishAds.conf -o XianYuAdBlock.conf
          curl -fsSL -H "User-Agent: Quantumult X" https://ddgksf2013.top/rewrite/StartUpAds.conf -o StartUpAdBlock.conf
          curl -fsSL -H "User-Agent: Quantumult X" https://ddgksf2013.top/rewrite/BiliBiliAdsLite.conf -o BiliBiliAdBlockLite.conf
          curl -fsSL -H "User-Agent: Quantumult X" https://ddgksf2013.top/rewrite/XiaoHongShuAds.conf -o XiaoHongShuAdBlock.conf
          curl -fsSL -H "User-Agent: Quantumult X" https://ddgksf2013.top/scripts/javdbapp.ads.js -o JavDBAdBlock.js
          curl -fsSL -H "User-Agent: Quantumult X" https://ddgksf2013.top/scripts/zhihu.ads.js -o ZhihuAdBlock.js

      - name: Commit and Push
        run: |
          NOW=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "chore: sync config files $NOW (UTC+8)"
            git push
          else
            echo "No changes detected, skipping push."
          fi
